/*
 *---------------------------------------------------------------------------------------------
 *  Copyright (c) Yarn Spinner Editor Team. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *---------------------------------------------------------------------------------------------
*/

import { app, BrowserWindow, Menu, ipcMain, shell, screen, dialog} from "electron";
import { openFile as YarnOpenFile } from "./controllers/fileSystem/fileOpenController";
import { writeFile as YarnWriteFile } from "./controllers/fileSystem/fileWriteController";

if (require("electron-squirrel-startup")) app.quit();

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

/**
 * Creates the main window. This is a change.
 * 
 * @returns {null} No return
 */
function createWindow() 
{

    // Create the browser window.
    // Create a window that fills the screen's available work area.
    const primaryDisplay = screen.getPrimaryDisplay();
    const { width, height } = primaryDisplay.workAreaSize;

    const mainWindow = new BrowserWindow({
        height: height - 50,
        width: width - 50,
        minHeight: 480,
        minWidth: 540,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
        }
    });


    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow.setTitle("Yarn Spinner Editor");
    // add event to prompt user if they exit without saving
    mainWindow.on("close", (e) =>
    {   
        e.preventDefault();
        requestUnsavedFiles();
    });

}

//https://www.electronjs.org/docs/api/menu
const isMac = process.platform === "darwin";

const template = [
    // { role: 'appMenu' }
    ...(isMac ? [{
        label: app.name,
        submenu: [
            { role: "about" },
            { type: "separator" },
            { role: "services" },
            { type: "separator" },
            { role: "hide" },
            { role: "hideothers" },
            { role: "unhide" },
            { type: "separator" },
            { role: "quit" }
        ]
    }] : []),
    // { role: 'fileMenu' }
    {
        label: "File",
        submenu: [
            { 
                label: "New",
                accelerator: "CmdOrCtrl+N",
                click: async () =>
                {
                    handleNewFile();
                } 
            },
            {
                label: "Open",
                accelerator: "CmdOrCtrl+O",
                click: async () => 
                {
                    handleFileOpen();
                }
            },
            { 
                label: "Save",
                accelerator: "CmdOrCtrl+S",
                click: async () =>
                {
                    handleFileSave();
                }
            },
            { 
                label: "Save As",
                accelerator: "CmdOrCtrl+Shift+S",
                click: async () =>
                {
                    handleFileSaveAs();
                }
            },
            isMac ? { role: "close" } : { role: "quit" },
        ]
    },
    // { role: 'editMenu' }
    {
        label: "Edit",
        submenu: [
            { 
                label: "Undo",
                accelerator: "CmdOrCtrl+Z",     //!Fails to get called
                click: async () =>
                {   
                    handleUndo();
                }
            },
            { 
                label: "Redo",
                accelerator: "CmdOrCtrl+Y",     //!Fails to get called 
                click: async () =>
                {
                    handleRedo();
                } 
            },
            { type: "separator" },
            { role: "copy" },
            { role: "cut" },
            { role: "paste" },
            { type: "separator" },
            { 
                label: "Find",
                accelerator: "CmdOrCtrl+F",
                click: async () =>
                {
                    handleFind();
                } 
            },
            { 
                label: "Replace",
                accelerator: "CmdOrCtrl+H",
                click: async () =>
                {
                    handleReplace();
                } 
            },
            ...(isMac ?
                [
                    { role: "pasteAndMatchStyle" },
                    { role: "selectAll" },
                    { type: "separator" },
                    {
                        label: "Speech",
                        submenu: [
                            { role: "startSpeaking" },
                            { role: "stopSpeaking" }
                        ]
                    }
                ] :
                [
                    { type: "separator" },
                    { role: "selectAll" }
                ])
        ]
    },
    // { role: 'viewMenu' }
    {
        label: "View",
        submenu: [
            { role: "reload" },
            { role: "forceReload" },
            { role: "toggleDevTools" },
            { type: "separator" },
            { role: "resetZoom" },
            { role: "zoomIn" },
            { role: "zoomOut" },
            { type: "separator" },
            { role: "togglefullscreen" }
        ]
    },
    // { role: 'windowMenu' }
    {
        label: "Window",
        submenu: [
            { role: "minimize" },
            { role: "zoom" },
            ...(isMac ? [
                { type: "separator" },
                { role: "front" },
                { type: "separator" },
                { role: "window" }
            ] : [
                { role: "close" }
            ])
        ]
    },
    // optionsMenu
    {
        label: "Options",
        submenu: [
            { label: "themes" },
            { label: "accessibility" },
            { label: "settings" },
            { label: "search" },
        ]
    },
    {
        label: "Help",
        submenu: [
            {
                label: "Yarn Spinner Documentation",
                click: async () => 
                {
                    await shell.openExternal("https://github.com/YarnSpinnerTool/YarnSpinner/blob/yarn-spec/Documentation/Yarn-Spec.md"); //TODO This will be changed to wherever the 2.0 docs are located 
                }
            },
            {
                label: "Editor bug?",
                click: async () => 
                {
                    await shell.openExternal("https://github.com/setho246/YarnSpinnerEditor/issues"); //TODO will need to change once ownership changes
                }
            },
        ]
    }
];

//@ts-expect-error Forge
const menu = Menu.buildFromTemplate(template);
Menu.setApplicationMenu(menu);

app.whenReady().then(createWindow);

/** 
 * Prevents the user from closing the application when there are files unsaved in the application.
 * 
 * @param {string} unsaved 2D array of unsaved files
 * @return {void}
 */
function returnSavePrompt(unsaved: string[][])
{
    let cancel = false;
    if (unsaved[0].length != 0)
    {
        //unsaved[0] = UID
        //unsaved[1] = name
        //unsaved[2] = path
        //unsaved[3] = contents

        for(let i = 0; i < unsaved[0].length; i++)
        {
            handleSetActiveFile(parseInt(unsaved[0][i]));   // displays the unsaved file in application
            const savePrompt = dialog.showMessageBoxSync(BrowserWindow.getAllWindows()[0],
                {
                    type: "warning",
                    buttons: ["Save","Don't Save","Cancel"],
                    defaultId: 0,
                    title: "Careful!",
                    message: "Do you want to save changes to " + unsaved[1][i] + "?",
                    noLink: true
                });
    
            switch (savePrompt) 
            {
            case 0:     // save
                YarnWriteFile(unsaved[2][i], unsaved[3][i]);
                handleFileSaved(parseInt(unsaved[0][i]));
                break;
    
            case 1:     // don't save
                break;
                
            default:    // do nothing
                cancel = true;
                break;
            }
            if(cancel) break;
        }
    }
    if(!cancel)
    {
        BrowserWindow.getAllWindows()[0].destroy();
    }
}

app.on("window-all-closed", () => 
{
    if (process.platform !== "darwin") 
    {
        app.quit();
    }
});

app.on("activate", () => 
{
    if (BrowserWindow.getAllWindows().length === 0) 
    {
        createWindow();
    }
});

// intended for mac
app.on("will-finish-launching", () => 
{
    app.on("open-file", (event, filePath) => 
    {
        event.preventDefault();
        handleFileOpen([filePath]);
    });
});

/*
	******************************************************************************************************************
										IPCMain Listeners and Emitters
	******************************************************************************************************************
*/

/*
	------------------------------------
				LISTENERS
	------------------------------------
*/

ipcMain.on("getPing", (event) => 
{
    //console.log(arg);
    event.reply("gotPing", "You're a curious one");
});

ipcMain.on("fileOpenToMain", (event, filePath) => 
{
    //console.log(filePath);
    handleFileOpen(filePath);
});

ipcMain.on("fileSaveToMain", (event, filePath, contents) => 
{
    const result = YarnWriteFile(filePath, contents);

    event.reply("fileSaveResponse", result.result, result.path, result.name);
});

ipcMain.on("returnUnsavedFiles", (event, unsaved) =>
{
    returnSavePrompt(unsaved);
});

/*
	------------------------------------
				EMITTERS
	------------------------------------
*/
//Sends from Main to Renderer
//BrowserWindow.getFocusedWindow()?.webContents.send("ChannelMessage", args);
//This should ONLY be used for menu interaction

//File Options
//----------------------------

/**
 * Emits message to renderer to create new file.
 * 
 * @returns {void}
 */
function handleNewFile() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestNewFile"); //Pass the result to renderer
}

/**
 * Handles the opening of a file and returns the contents to the focused window.
 * 
 * @param {string} filePath source of file (if available)
 * @returns {void}
 */
function handleFileOpen(filePath? : string[]) 
{
    //Sends message from main to renderer
    const fileContent = YarnOpenFile(filePath);
    if(fileContent) 
    {        
        BrowserWindow.getAllWindows()[0].webContents.send("openFile", fileContent); //Pass the result to renderer
    }
}

/**
 * Emits message to renderer to save the file.
 * 
 * @returns {void}
 */
function handleFileSave() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestSave"); 
}

/**
 * Emits message to renderer to saveAs the file.
 * 
 * @returns {void}
 */
function handleFileSaveAs() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestSaveAs"); 
}

/**
 * Emits a message to renderer to receive unsaved files in the FileManager, replies by calling "returnUnsavedFiles".
 * 
 * @returns {void}
 */
function requestUnsavedFiles()
{
    BrowserWindow.getAllWindows()[0].webContents.send("mainRequestUnsavedFiles");
}

/**
 * Emits a message to renderer to transition to a file in working files.
 * 
 * @param {number} yarnFileUID id of yarn file to set as active
 * @returns {void}
 */
function handleSetActiveFile(yarnFileUID : number)
{
    BrowserWindow.getAllWindows()[0].webContents.send("setOpenFile", yarnFileUID);
}

/**
 * Emits a message to confirm that the file was written.
 * Used for save prompt case only.
 * 
 * @param {number} yarnFileUID id of the yarn file to report saved
 * @returns {void}
 */
function handleFileSaved(yarnFileUID : number)
{
    BrowserWindow.getAllWindows()[0].webContents.send("setFileSaved", yarnFileUID);
}

//Edit Options
//----------------------------

/**
 * Emits message to renderer to find the selected code within the file.
 * 
 * @returns {void}
 */
function handleFind() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestFind"); 
}

/**
 * Emits message to renderer to replace the selected code within the file.
 * 
 * @returns {void}
 */
function handleReplace() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestFindAndReplace"); 
}

/**
 * Emits a message to renderer to undo any changes made in the code
 * 
 * @returns {void}
 */
function handleUndo() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestUndo"); 
}

/**
 * Emits a message to renderer to redo any changes made in the code
 * 
 * @returns {void}
 */
function handleRedo() 
{
    BrowserWindow.getFocusedWindow()?.webContents.send("mainRequestRedo"); 
}